name: Midnight Breakfast
permalink: /:title/
markdown: kramdown
redcarpet:
  extensions:
    - smart
kramdown:
  input: GFM
picture:
  source: "assets/images/_full"
  output: "generated"
  markup: "picturefill"
  presets:
    default:
#      ppi: [1, 1.5, 2]
      attr:
        class: "image"
        itemprop: "image"
#      source_xxxlarge:
#        media: "(min-width: 1400px)"
#        width: "2000"
#      source_xxlarge:
#        media: "(min-width: 1000px)"
#        width: "1400"
#      source_xlarge:
#        media: "(min-width: 800px)"
#        width: "1000"
#      source_large:
#        media: "(min-width: 600px)"
#        width: "800"
      source_medium:
        media: "(min-width: 400px)"
        width: "600"
      source_default: 
        width: "400"
    thumb:
#      ppi: [1, 1.5, 2]
      attr:
        class: "thumb"
        itemprop: "thumb"
#      source_xlarge:
#        media: "(min-width: 1000px)"
#        width: "800"
#        height: "400"
      source_large:
        media: "(min-width: 600px)"
        width: "600"
        height: "300"
      source_default: 
        width: "500"
        height: "250"
gems:
  - jekyll-compass