name: Midnight Breakfast
permalink: /:title/
relative_permalinks: false
markdown: kramdown
source: _src
destination: _site
kramdown:
  input: GFM
picture:
  source: "assets/images/full"
  output: "generated"
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 1.5, 2]
      attr:
        class: "image"
        itemprop: "image"
      source_xxlarge:
        media: "(min-width: 1000px)"
        width: "1200"
      source_xlarge:
        media: "(min-width: 800px)"
        width: "1000"
      source_large:
        media: "(min-width: 600px)"
        width: "800"
      source_medium:
        media: "(min-width: 400px)"
        width: "600"
      source_default: 
        width: "400"
    thumb:
      ppi: [1, 1.5, 2]
      attr:
        class: "thumb"
        itemprop: "thumb"
      source_large:
        media: "(min-width: 600px)"
        width: "400"
        height: "200"
      source_default: 
        width: "300"
        height: "150"
gems:
  - jekyll-compass